### ISSUE TITLE
How to customize Product View

### ISSUE THREAD

**Issue by sinkcup** [russell-archer/StoreHelper#12]
this package provider a `Products` list view, but I need a simpler view for only one subscription, just like Apple Docs:

![image](https://user-images.githubusercontent.com/4971414/196592909-03d6157c-42f8-4155-83a0-ede89e03e9b9.png)

so I write a view using PurchaseButton:

```
    var body: some View {
        if storeHelper.hasSubscriptionProducts, let subscriptions = storeHelper.subscriptionProducts {
            ForEach(subscriptions, id: \.id) { subscription in
                VStack {
                    Text(subscription.displayName)
                    Text(subscription.description)
                    PurchaseButton(purchaseState: $purchaseState, productId: productId, price: subscription.displayPrice)
                }
            }
        }
    }
```

but error:

> 'PurchaseButton' initializer is inaccessible due to 'internal' protection level

![image](https://user-images.githubusercontent.com/4971414/196592255-714a11eb-20d7-4ff6-823a-cd88e8308966.png)

so, how to customize Product View?

**Comment by russell-archer** [comment]
Yes, you're right! I've had a quick look at fixing it but there isn't a quick fix as PurchaseButton itself uses a number of other internal views such as PriceView, PriceButtonText, BadgeView, etc. And to make them all publically accessible I'll need to make other changes. 

What you've highlighted is that the UI parts of StoreHelper aren't yet fully customizable, as they would be in a commerical product. I'll spend some time as soon as I can to address this. In the meantime, I suggest that you copy the code for PurchaseButton, PriceView, PriceButtonText and BadgeView into your project and rename them as CustomPurchaseButton, CustomPriceView, etc. I've tried this and everything compiles OK and purchases work just fine.

**Comment by russell-archer** [comment]
Done. Refactored views to have public initializers so individual views may be used to create a custom UI.
