### ISSUE TITLE
show SubscriptionPeriod on PurchaseButton

### ISSUE THREAD

**Issue by sinkcup** [russell-archer/StoreHelper#13]
storeKit `Product` has column `SubscriptionPeriod`, can be used on `PurchaseButton`.

now:

<img width="119" alt="image" src="https://user-images.githubusercontent.com/4971414/196605632-ba7aa18d-994c-4ebc-b5ba-9f1897c050d5.png">

expect:

![image](https://user-images.githubusercontent.com/4971414/196605795-011d3f1a-4d88-4ccc-8e97-4e71bc0309fe.png)

**Comment by sinkcup** [comment]
notice: apple web docs is wrong. https://developer.apple.com/documentation/storekit/skproductsubscriptionperiod/2936876-numberofunits

```
subscription.subscription?.subscriptionPeriod.numberOfUnits
```

> Value of type 'Product.SubscriptionPeriod' has no member 'numberOfUnits'

should use:

```
subscription.subscription?.subscriptionPeriod.value
```

```
PurchaseButton(purchaseState: $purchaseState, productId: productId, price: subscription.displayPrice + " / " + period)

self.period = subscription.subscription?.subscriptionPeriod.unit.localizedDescription ?? ""
                    let periodValue = subscription.subscription?.subscriptionPeriod.value ?? 1
                    if periodValue != 1 {
                        // TODO Month to Months
                        self.period = String(periodValue) + " " + self.period
                    }
```

**Comment by russell-archer** [comment]
Excellent suggestion! It looks much better when the period is shown on the button. I'll implement your idea as a configurable option (so as not to break exisiting code)
