### ISSUE TITLE
Products not loading fast enough ..

### ISSUE THREAD

**Issue by jamestapping** [russell-archer/StoreHelper#16]
Hiya,

I have everything pretty much working with your framework now so thanks for your hard work, and great documentation.
I haven't been able load the products as any point in the life Cycle early enough to not get a "need to refresh message" showing for a second or two. Is this normal ?
And if so , would it be possible to change the message to a ProgressView instead?
I hacked one myself :) Which is more reassuring than the nasty red message :-)

Thanks very much 

James

**Comment by russell-archer** [comment]
Fixed an issue where a red error about no products being available was displayed while waiting for a response from the app store. A spinner (ProgressView) is now displayed while StoreHelper is actively waiting for a response. The error about no products is only displayed when the app store returns a response with zero products
