### ISSUE TITLE
Could not fetch Products array (tvOS)

### ISSUE THREAD

**Issue by rebeloper** [russell-archer/StoreHelper#2]
In requestProductsFromAppStore on tvOS, debug mode (not yet live on the App Store) I get a failure of requestProductsFailure either by having nil Products or an empty array of Products.

The same happens on watchOS production mode, while it works ok in debug.

I narrowed down the issue to the line `try? await Product.products(for: productIds)`

It seems that there's a bug in StoreKit2 🤔

Any thoughts?

**Comment by russell-archer** [comment]
Hi Alex

Away from my machine at the moment but will look into it in a couple of hours. 

One thing to check is if productIds actually has a set of ids or not. If not, it’s something to do with the property file containing your product ids not being read. If it does have ids then it sounds like a pretty fundamental StoreKit2 bug. 

Russell

**Comment by russell-archer** [comment]
I can confirm I’m seeing the same problem as you are for tvOS on the simulator.
The configuration file is being correctly read and the product ids are being returned OK.
However, as you say, the call to try? await Product.products(for: productIds) fails. If you retry you get the same error. Interestingly, the first time you request localized product info the call doesn’t seem to return. If you you retry the call then it immediately fails and StoreHelper is able to log an error (Request products from the App Store failure).

I’m also seeing the following error:
[StoreKit] Failed to get products through appstored in simulator, will try using appstoreagent on host mac:
Error Domain=ASDErrorDomain Code=507 "Error decoding response" UserInfo={NSLocalizedDescription=Error decoding response, NSLocalizedFailureReason=Could not decode media products response}

This does indeed look like a bug in StoreKit2.

I’ll do some more playing with this over the weekend and see if I can workaround the issue!

Russell

**Comment by russell-archer** [comment]
After more investigation I've found that using a real Apple TV device also fails at the same point when requesting localized products. However, I do get an additional error that I don't see when running on the TV simulator:

void * _Nullable NSMapGet(NSMapTable * _Nonnull, const void * _Nullable): map table argument is NULL

So, I've verified that from a StoreHelper perspective everything runs as expected on tvOS until the point where 

try? await Product.products(for: ids) 

is called. When the async call is made it doesn't return for about 10-15 seconds, and then times out with an error from StoreKit. For me this happens on both the tvOS simulator and a real Apple TV device. The exact same code runs perfectly on iOS and macOS. I haven't tested it on watchOS yet. I'm afraid this really seems like a StoreKit2 bug. I'll leave this issue open but without input/help from Apple I'm not sure how to proceed with fixing this as it's such a fundamental problem.

**Comment by rebeloper** [comment]
Got to the same tests and conclusion myself :) Hopefully Apple will fix this issue with an update. Thanks for your research

**Comment by rebeloper** [comment]
watchOS works. I found my error was in iOS Deployment Target, in my project was with compatibility from iOS 13, I change to iOS 15 because StoreKit 2 works only with this version but is very strange because my app only works in WatchOS without iPhone dependencies.

**Comment by russell-archer** [comment]
This seems to have been fixed by Apple in StoreKit 2 released with Xcode 14.
