### ISSUE TITLE
how to check subscribed on first View

### ISSUE THREAD

**Issue by sinkcup** [russell-archer/StoreHelper#22]
I want show content or notice subscription on the App's first View, so I need check subscribed first.

but `storeHelper.start()` is a async function, so the `storeHelper.subscriptionProductIds` is empty, and can not check subscribed.

![image](https://user-images.githubusercontent.com/4971414/201923400-e40fe7eb-7036-400f-98f5-30599b8c6cbd.png)

**Comment by russell-archer** [comment]
Yes, you can't things the way you're attempting it. I would suggest having storeHelper.start() in your @main App struct and then have checks for products being purchased or subscribed in the first view that's displayed.

For example, see SimplePurchaseView() in StoreHelperDemo (https://github.com/russell-archer/StoreHelperDemo). That view could be called directly from your App struct. SimplePurchaseView() shows how to check for a non-consumable product purchase but the same thing would work for a subscription:

@main
struct YourApp: App {
    @StateObject var storeHelper = StoreHelper()
    
    var body: some Scene {
        WindowGroup {
            YourFirstView().environmentObject(storeHelper)
                .task { storeHelper.start() }
        }
    }
}
