### ISSUE TITLE
support Xcode 14 for iOS 15

### ISSUE THREAD

**Issue by sinkcup** [russell-archer/StoreHelper#25]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/4971414/202846684-4686a3fd-1ca9-4d36-8b07-ccf2807f47a3.png">

https://developer.apple.com/support/app-store/

now 82% iOS users is using iOS 15, I have saw StoreHelper docs:

> using Xcode 14 to easily add in-app purchase support to iOS 16/macOS 13 SwiftUI apps. Xcode 13 with iOS 15/macOS 12 are also supported.

I am using Xcode 14 on macOS 13, I try to download Xcode 13, but run failed.

![image](https://user-images.githubusercontent.com/4971414/202847685-ec7c12b6-576d-4a12-a99c-d2dcdfea7608.png)

![image](https://user-images.githubusercontent.com/4971414/202847948-0b543663-46e0-4a9e-95a0-7887c78b8d23.png)

so I have to use Xcode 14 to develop app for iOS 15, does StoreHelper support it?

**Comment by russell-archer** [comment]
Yes, StoreHelper supports iOS 15 and 16 with Xcode 13 and 14. Russell Sent from my iPhoneOn 19 Nov 2022, at 11:17, sink ***@***.***> wrote:﻿

https://developer.apple.com/support/app-store/
now 82% iOS users is using iOS 15, I have saw the docs:

using Xcode 14 to easily add in-app purchase support to iOS 16/macOS 13 SwiftUI apps. Xcode 13 with iOS 15/macOS 12 are also supported.

I am using Xcode 14 on macOS 13, I try to download Xcode 13, but run failed.


so I have to use Xcode 14 to develop app for iOS 15, does StoreHelper support it?

**Comment by sinkcup** [comment]
great! Maybe the docs sould be changed

**Comment by russell-archer** [comment]
I *thought* I’d updated all the various readme and other documents to state that iOS 15/16, macOS 12/13 and Xcode 13/14 were supported.
I’d appreciate it if you’d let me know if you’ve found somewhere that I’ve missed!

**Comment by sinkcup** [comment]
> StoreHelper is a Swift Package Manager (SPM) package that enables developers using Xcode 14 to easily add in-app purchase support to iOS 16/macOS 13 SwiftUI apps. Xcode 13 with iOS 15/macOS 12 are also supported.

suggestion:

> StoreHelper is a Swift Package Manager (SPM) package that enables developers using Xcode 14/13 to easily add in-app purchase support to iOS 16/15 and macOS 13/12 SwiftUI apps.
