### ISSUE TITLE
AppStore.showManageSubscriptions() sync issue

### ISSUE THREAD

**Issue by ashayk** [russell-archer/StoreHelper#27]
Hi,

When using AppStore.showManageSubscriptions() to cancel or change subscriptions, I'm not getting any  subsequent Transaction updates and no change in the isPurchased() status regardless of what I do in the subscription sheet. Tested in Simulator with 16.1 and a local Product store configuration file. Any guidance would be appreciated.

Thanks.

**Comment by russell-archer** [comment]
I’ll take a look and see if I can replicate the issue and get back to you. On 3 Dec 2022, at 20:06, ashayk ***@***.***> wrote:﻿
Hi,
When using AppStore.showManageSubscriptions() to cancel or change subscriptions, I'm not getting any  subsequent Transaction updates and no change in the isPurchased() status regardless of what I do in the subscription sheet. Tested in Simulator with 16.1 and a local Product store configuration file. Any guidance would be appreciated.
Thanks.

**Comment by russell-archer** [comment]
I can't reproduce the issues you're seeing. All seems to be as expected.

To test I used the simulator and the StoreHelperDemo project. Using Xcode 14.1 (14B47b) with the latest build of StoreHelper and the StoreHelperDemo project. Minimum deployment target set to iOS 16.0. Running on macOS Ventura 13.0.1. I set the renewal period to be 30 seconds and then I did the following:

- Subscribed to the 'silver' product
- StoreHelper correctly showed me as subscribed
- Tapped on the subscription info button to display the subscription data
- Tapped on the 'Manage Subscription' button and cancelled the subscription
- After 30 seconds or so the StoreHelper correctly showed the subscription as cancelled
- Subscribed to the 'silver' product again
- StoreHelper correctly showed me as subscribed
- Tapped on the subscription info button, then tapped 'Manage Subscription' and upgraded the subscription to 'gold'
- StoreHelper correctly showed me as subscribed to the 'gold' product
- Let the subscription auto-renew a couple of times
- Everything as expected and the subscription correctly renewed
- All the transactions displayed in the StoreKit Transactions window were exactly what I'd expect

So, everything appears to be correct. 

One thing to note, Apple's documentation says that the SwiftUI `.manageSubscriptionsSheet(isPresented:)` doesn't work correctly in the StoreKit Testing environment. StoreHelper logs a warning to that affect. They say the same thing about the `.refundRequestSheet(for:isPresented:)` modifier. They always both seem to work OK for me. If you're still seeing the same thing, maybe you could try running in the sandbox environment with a real device?

**Comment by ashayk** [comment]
Hi Russel,

Thanks for the very quick turnaround. I'm going to update XCode and try again. I've had a bit of strange behaviour, so it all might be related to that rather than StoreHelper. I'm encouraged that things are working well on your end, so I'll keep working to get it going.
