### ISSUE TITLE
TermsOfServiceView is not using the config overrides

### ISSUE THREAD

**Issue by drallgood** [russell-archer/StoreHelper#30]
Doesn't seem connected because the params never get passed to the view and so it uses the defaults
See https://github.com/russell-archer/StoreHelper/blob/455ad0e61f55e3bcdc752f643c44220cb6700364/Sources/StoreHelper/Views/iOS/Products-ios.swift#L73

**Comment by russell-archer** [comment]
Fixed.

**Comment by drallgood** [comment]
Thanks!
