### ISSUE TITLE
Revocation not handled properly

### ISSUE THREAD

**Issue by drallgood** [russell-archer/StoreHelper#33]
While investigating a different issue (subscription purchases don't seem to work correctly.. looks like an iOS bug) I stumbled upon this line:
https://github.com/russell-archer/StoreHelper/blob/267b0342d8fed38d68f1a3a57f5add38602a10c8/Sources/StoreHelper/Core/StoreHelper.swift#L540

shouldn't this be `!= nil`? i.e. it's added unless it was revoked?

**Comment by russell-archer** [comment]
Well spotted! You're right. I accidentally introduced this bug a few days ago. Thanks very much for the feedback. Fixed!

**Comment by drallgood** [comment]
> Well spotted! You're right. I accidentally introduced this bug a few days ago. Thanks very much for the feedback. Fixed!

Awesome! Thanks for the quick fix!
