### ISSUE TITLE
Compile error: Configuration has no member named "value" 

### ISSUE THREAD

**Issue by charvoa** [russell-archer/StoreHelper#39]
RestorePurchaseView-ios:22 

Here is the non-compiling line : 

` if let restorePurchasesButtonText = Configuration.restorePurchasesButtonText.value(storeHelper: storeHelper) {`

**Comment by russell-archer** [comment]
Oops! Made some changes yesterday and thought I'd tested on iOS and macOS. Seems I forgot to test on iOS! Fixed now, but I think I need to create some automated tests ;-)
