### ISSUE TITLE
Subscription group

### ISSUE THREAD

**Issue by reza11331** [russell-archer/StoreHelper#40]
Hi,

I am encountering an issue retrieving subsection info. Since I already have my app on app store, there's not way for me to adopt the subscriptions Id to the give format (com.{developer}.subscription.{subscriptionGroupName}.{productName})
Isn't there an alternative way to get the info for a subscription group?

**Comment by russell-archer** [comment]
Hi Reza,

That naming convention for subscriptions was chosen so the developer doesn’t have to create yet another configuration file. For example, when you’re processing subscriptions you have to know things like the subscription group name. From memory, I think it would be possible in future versions to do everything required without using that convention. However, at present StoreHelper totally relies on the subscription naming convention to do various things.

So, the short answer is currently no, StoreHelper won’t work for you. When I have some spare time I’ll take a look if I can remove the need for the convention.

Russell

**Comment by russell-archer** [comment]
In-progress

**Comment by russell-archer** [comment]
Complete. Available in version 2.3 onwards. See Samples > Configuration > SampleProducts.plist for details.
