### ISSUE TITLE
Missing repository reference

### ISSUE THREAD

**Issue by chriswitko** [russell-archer/StoreHelper#45]
Hi, 

I'm trying to add https://github.com/russell-archer/StoreHelper to my project, however not sure why the only repository that is found is StoreHelperDemoUIKit. Do you know why the main repo is missing?

<img width="1070" alt="Screenshot 2023-02-06 at 20 45 01" src="https://user-images.githubusercontent.com/566215/217069893-3e0b6f65-3ce1-4a37-a73c-1dd37bd99079.png">

**Comment by russell-archer** [comment]
That's very weird. I can't reproduce the issue you're seeing. I just create a new multi-platform project with Xcode 14.2 and did **Add Packages**. Pasted the URL for the package and it worked just fine:

![sh-2023-02-06_22-07-44](https://user-images.githubusercontent.com/6470403/217099579-151671a1-411e-468b-9c51-8d3ec258bcff.png)

![sh-2023-02-06_22-07-59](https://user-images.githubusercontent.com/6470403/217099600-e3be989b-4f07-4aa5-a9c5-b45a1114628d.png)

![sh-2023-02-06_22-08-25](https://user-images.githubusercontent.com/6470403/217099626-5ed992c1-0501-40d4-aec8-941132316148.png)

And the Package.swift file is definately there OK.

**Comment by chriswitko** [comment]
@russell-archer thank you for your comment. It's definitely something with Xcode and fetching data from GitHub, but what helped me is the use of git@github.com:russell-archer/StoreHelper.git instead https

**Comment by russell-archer** [comment]
Ah, good idea using git@github.com! I'll add that to the documentation. Thanks for lettingme know!
