### ISSUE TITLE
isPurchased() can't be called right after start()

### ISSUE THREAD

**Issue by akirmse** [russell-archer/StoreHelper#5]
I'm trying to determine if the user has purchased a subscription, e.g. on a previous run of the app.  So I call:

```
            await storeHelper.start()
            
            // Update our knowledge of what products are purchased
            do {
                try await storeHelper.isPurchased(productId: PRO_PRODUCT_ID)
```

However, ```start()``` starts an async task, and ```isAppStoreAvailable``` isn't true until the task has finished, meaning that ```isPurchased``` fails right away, because ```isAppStoreAvailable``` is false.

I need to know if the subscription has been purchased to show or hide a feature in the UI without waiting for a network request, so I make these calls at app startup so that the purchase will be cached in ```purchasedProductsFallback```, which I can check quickly.

What's the right way to do this with StoreHelper?

**Comment by russell-archer** [comment]
Hi Andrew,

There’s a few ways to accomplish what you’re looking for.

You can check if a subscription has been purchased in the App struct:

import SwiftUI
import StoreHelper

@main
struct StoreHelperSubDemoApp: App {
    @StateObject var storeHelper = StoreHelper()
    @State private var productIds: [ProductId]?  // IAPs available from the AppStore
    
    var body: some Scene {
        WindowGroup {
            ContentView()
                .environmentObject(storeHelper)
                .task {
                    storeHelper.start()  // Get product info from the App Store
                }
                .onChange(of: storeHelper.products) { _ in
                    // We've got an updated list of available IAPs from the AppStore
                    productIds = storeHelper.subscriptionProductIds  // Get just our subscriptions
                    print("Products changed. \(productIds?.count ?? 0) subscriptions now available from the AppStore.")
                    
                    // Has the "Gold" subscription been purchased?
                    Task.init {
                        if let productPurchased = try? await storeHelper.isPurchased(productId: "com.rarcher.subscription.vip.gold") {
                            print("The Gold subscription has \(productPurchased ? "" : "not") been pruchased")
                        }
                    }
                }
        }
    }
}

Alternatively, you could check in the initial view:

import SwiftUI
import StoreHelper

@main
struct StoreHelperSubDemoApp: App {
    @StateObject var storeHelper = StoreHelper()
    
    var body: some Scene {
        WindowGroup {
            ContentView()
                .environmentObject(storeHelper)
                .task {
                    storeHelper.start()  // Get localized product info from the App Store
                }
        }
    }
}

struct ContentView: View {
    @EnvironmentObject var storeHelper: StoreHelper
    @State private var productIds: [ProductId]?
    
    var body: some View {
        VStack {
            // Display the purchase state for all subscription products
            if let pids = productIds {
                ForEach(pids, id: \.self) { pid in
                    SubscriptionRow(productId: pid)
                    Divider()
                }

                Spacer()
            } else {
                Text("You don't have any subscription products")
                    .font(.title)
                    .foregroundColor(.red)
            }
        }
        .padding()
        .onChange(of: storeHelper.products) { _ in
            productIds = storeHelper.subscriptionProductIds
        }
    }
}

struct SubscriptionRow: View {
    @EnvironmentObject var storeHelper: StoreHelper
    @State private var isSubscribed = false
    @State private var detailedSubscriptionInfo: ExtendedSubscriptionInfo?
    var productId: ProductId
    
    var body: some View {
        VStack {
            HStack {
                Text("You are \(isSubscribed ? "" : "not") subscribed to \(productId)")
                    .foregroundColor(isSubscribed ? .green : .red)
                    .multilineTextAlignment(.center)
                    .padding()
            }
            
            if isSubscribed, let info = detailedSubscriptionInfo {
                Text("Your subscription to \(info.name) renews in \(info.renewsIn ?? "unknown")").multilineTextAlignment(.center)
                // Display more subscription info here...
            }
        }
        .task {
            isSubscribed = await subscribed(to: productId)
            if isSubscribed {
                if let subscriptionInfo = await getSubscriptionInfo() {
                    detailedSubscriptionInfo = await getDetailedSubscriptionInfo(for: subscriptionInfo)
                }
            }
        }
    }
    
    private func subscribed(to productId: ProductId) async -> Bool {
        let productPurchased = try? await storeHelper.isPurchased(productId: productId)
        return productPurchased ?? false
    }
    
    private func getSubscriptionInfo() async -> SubscriptionInfo? {
        var subInfo: SubscriptionInfo?
        
        // Get info on all subscription groups (this demo only has one group called "VIP")
        let subscriptionGroupInfo = await storeHelper.subscriptionHelper.groupSubscriptionInfo()
        if let vipGroup = subscriptionGroupInfo?.first, let product = vipGroup.product {
            // Get subscription info for the subscribed product
            subInfo = storeHelper.subscriptionHelper.subscriptionInformation(for: product, in: subscriptionGroupInfo)
        }
        
        return subInfo
    }
    
    private func getDetailedSubscriptionInfo(for subInfo: SubscriptionInfo) async -> ExtendedSubscriptionInfo? {
        let viewModel = SubscriptionInfoViewModel(storeHelper: storeHelper, subscriptionInfo: subInfo)
        return await viewModel.extendedSubscriptionInfo()
    }
}


Hope this helps!

Best wishes

Russell

**Comment by akirmse** [comment]
Thanks.  I'm not using SwiftUI, and this code isn't inside a View, but I think I was able to achieve roughly the same thing manually.  I still have to check whether the asynchronous ```storeHelper.start()``` task has finished by calling ```hasStarted```:

```
    static func runAtStartup() {
        Task {
            await storeHelper.start()
            
            // When list of products changes, see what's purchased
            productsSink = storeHelper.$products.sink() { _ in
                if storeHelper.hasStarted {  // Wait until async startup completes
                    Task.init {
                        await updateKnownPurchasedProducts()
                    }
                }
            }
        }
    }
```
