### ISSUE TITLE
How to implement custom transaction handler

### ISSUE THREAD

**Issue by misteral** [russell-archer/StoreHelper#52]
Hello. 

Please, recommend me the best way to implement a custom event, specifically for analytic purchase state after a purchase button has been clicked.

Thanks.

**Comment by russell-archer** [comment]
Does this work for you? If so, I'll close the issue.

**Comment by misteral** [comment]
@russell-archer Hi, I just got back to my app now. Yes, it looks like it should work for me. Thanks.
