### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by cjarman** [russell-archer/StoreHelper#53]
Hi,

XCode is throwing a compilation error:

_Missing arguments for parameters 'content', 'publisher', 'action' in call_

This from the MainView on the following line from the demo app:

`NavigationLink(destination: SubscriptionView()) { Text("Subscriptions").font(.largeTitle).padding()}`

SubscriptionView does not appear to take any parameters.

C

**Comment by russell-archer** [comment]
Sorry, can't reproduce this. To test I opened the StoreHelperDemo project, did  File > Packages > Update to Latest Package Versions to make sure I was using the latest version of StoreHelper and then rebuilt for iOS (16.2) and macOS (13.1). I also built for iOS 16.4 and macOS 13.3 without an errors. This is was using Xcode 14.3 on macOS 13.3.1.
