### ISSUE TITLE
Can I use this without having the local Product.plist configuration file?

### ISSUE THREAD

**Issue by brainfuel** [russell-archer/StoreHelper#59]
IAP products are regularly updated in my app and I retrieve them from our server. Am I forced to use the local Product.plist configuration file? 

I see requestProductsFromAppStore(productIds which returns me the correct Products but when I check storeHelper.products?.count
It's always 0.

**Comment by Bankrollshow** [comment]
#57

**Comment by russell-archer** [comment]
Currently you are indeed forced to use a local Products.plist. I'll implement an enhancement to allow StoreHelper to get products from a server.

**Comment by russell-archer** [comment]
Will not make these changes as I'm developing a more modern, lightweight StoreKit helper that is based around StoreKit Views. Details to follow.

**Comment by NikKovIos** [comment]
@brainfuel  This is mandatory for my project too. 

@russell-archer  Are you telling about https://github.com/russell-archer/SKHelper/?
