### ISSUE TITLE
Log clashes for different transactions due to missing transactionID in TransactionLog 

### ISSUE THREAD

**Issue by smartinrub** [russell-archer/StoreHelper#60]
I think the `transactionID` should be included in the the `TransactionLog`, otherwise a particular event for a particular product only logs the first transaction.

Here is where the `TransactionLog` is created: [let t = TransactionLog(notification: event, productId: productId)](https://github.com/russell-archer/StoreHelper/blob/8c6e0d03269c33a096241d6b5b78226487f1fd30/Sources/StoreHelper/Core/StoreLog.swift#L67)

This can be easily reproduced on Xcode with a short renewal rate.

**Comment by russell-archer** [comment]
Will add as an enhancement!

**Comment by russell-archer** [comment]
Will not make these changes as I'm developing a more modern, lightweight StoreKit helper that is based around StoreKit Views. Details to follow.
