### ISSUE TITLE
Update package version 2.62.0 but used 2.6.3

### ISSUE THREAD

**Issue by Volodymyr-13** [russell-archer/StoreHelper#72]
Hey,

I just added StoreHelper into a simple blank project and got this: 

![Screenshot 1](https://github.com/russell-archer/StoreHelper/assets/3391456/d2abf72a-e5c2-4a3b-9f46-a46a3a6c5682)

Nothing special, just manually set 2.6.3 but it still 2.62.0 for some reason.. any ideas?

**Comment by russell-archer** [comment]
Hmmm that's weird. I just tried specifying version 2.6.3 and I also got 2.62 (that version number/tag was an error - should have been 2.6.2). I think the problem is that Xcode thinks version 2.62 is higher that 2.6.3 (and I guess it's right). I think I'll have to remove release 2.62.

**Comment by Volodymyr-13** [comment]
Hmm, it's still showing me 2.62.0 when 2.6.3 specified, clearing cache Reset Package Caches doesn't help.. maybe I have to try again later..

**Comment by Volodymyr-13** [comment]
Ok, checked again, fixed, thanks!

**Comment by russell-archer** [comment]
Great! Thanks very much for testing!!
