### ISSUE TITLE
Why the file size is more than 300MB

### ISSUE THREAD

**Issue by fifyrio** [russell-archer/StoreHelper#80]
Hi, Russell, my Mac is only 512GB, so could you please resize the project
![image](https://github.com/user-attachments/assets/3cbc449e-d180-440b-a651-c58c56de5819)

**Comment by russell-archer** [comment]
I'm not sure where that 300MB figure comes from, however, if I look at the size of the StoreHelper/Sources folder it's only 15MB. And looking at StoreHelperDemo the entire project's only 14MB. 

In terms of what's going on in your derived data directory I can't say. I don't think it can be StoreHelper-related as it's basically just a bunch of Swift sources files. There are a few images in the project related to DocC documentation, but they won't end up in your derived data. So, sorry I don't think there's anything I can do to reduce the size of the package.

And if you've got a 512GB drive you're lucky, I've only got 256GB!!

**Comment by fifyrio** [comment]
Thanks Russell for your reply, I will try other ways to save Spaces

**Comment by fifyrio** [comment]
Hi, Russell, I found that when I use my iPhone13 for debugging, it will install all the StoreHelper DocC Documents, and it will cost almost 5 minutes to install my app, so do you know why it copy the  DocC Documents to my iPhone13, thanks
![image](https://github.com/user-attachments/assets/1a52c3d8-7b9b-48cd-897d-6ad497e7b2a8)

**Comment by fifyrio** [comment]
It's my fault after I removed the `.build`, it fixed
![image](https://github.com/user-attachments/assets/f80baa61-001b-43ef-9390-42b7a7ed26aa)

**Comment by russell-archer** [comment]
That’s great, many thanks for letting me know!
